sudo: required
dist: trusty
language: node_js
node_js:
- node
before_script:
- npm install
script:
- npm test
deploy:
  app: lol-lametric
  provider: heroku
  api_key:
    secure: wy9mkUNVLtU7rjkp/4B/C43kRA3r0nlCXNZ252ZJSuyHYmvakZ8DfVpZB1jHQ0pWa1kZodKpNYJbrd+S/N24AoIUn6neQasUWSrz3Ocuuy2N4oizXZf7DV+xS6G7IUl5IfsNYKhNdCNmKeLB+cGGf7geJ8RwmNXBxXwArtNjVOhSILj4wpJWFVZh4m7LeYSsyk7fu8eeSL/3TRVfQZTjRT8m+sj9HKRBQBbpCB3dWFRBOAAOXJe31u7dCtr4Cn2NW63H3Dk+4G3zYx85ptkOf6KNLghBx5hIMFtDCzb8hK0RiD0XDhwdcuh3PpBxoWTk0+A6O31gYf5n5G/7Ddj1CvFyAB/fdCyg808vERCA+IqJKUf/hCU1Y/jDFk1ZM/tzaWZITYKpJdwGSY+NU3y8JJBDYHS9JwsPwD6RqVkoZVSG9oZs/qIpi4dNDD8zPSKIwNFWYUJPLvMuz72KpShHZUZNog44rmQdKLtGoHOm83KShff/OxI1T9g3S7r26ZDasl1ptzDdsnIQI5gPu3wmypL1uM738Hm8t69pFewNPrg7zfMRQLdqufRF6kf2jrxLZ325I0CQHHYCDlx96LdiMDTNl9QR82/1fuFOy9N9e07uOLbT/Yx8X1Pb6qxgX3NRPB/HIWof14GBF2vf9MX6PnF3gLZGLY4IV3/agJeUpYI=
